version: '3'

networks:
  prodnetwork:
    driver: bridge

services:
  apacheapp:
    image: 34.69.111.201:8082/cloudapprepo/myapache:2
    restart: always
    ports:
      - "9999:80"
    networks:
      - prodnetwork
  postgresdb:
    networks:
      - prodnetwork
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres123
